server:
  port: 8079
spring:
  #session:
  #store-type: redis
  #timeout: 3600
  redis:
    password: Redis20868354
    #    # 哨兵集群配置
    #    sentinel:
    #      master: mymaster
    #      nodes:
    #        - 192.168.5.106:26379
    #        - 192.168.5.106:26380
    #        - 192.168.5.106:26381
    # 连接池配置
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      cluster:
        refresh:
          # 自适应拓扑刷新
          adaptive: true
          # 定时刷新
          period: 2s
    # cluster集群配置
    cluster:
      max-redirects: 3
      nodes:
        - 192.168.5.106:6379
        - 192.168.5.106:6380
        - 192.168.5.106:6381
        - 192.168.5.106:6382
        - 192.168.5.106:6383
        - 192.168.5.106:6384
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL20868354

rocketmq:
  name-server: localhost:9876
  producer:
    group: kotlin-group # 当前应用是一个生产者，属于"kotlin-group"消费者组
    send-message-timeout: 300000 # 超时时间
    compress-message-body-threshold: 4096 # 压缩消息的阈值：4kb
    max-message-size: 4194304 # 消息最大4MB
    retry-times-when-send-failed: 2 # 发送失败后重试两次
    retry-next-server: true # 失败重试
    retry-times-when-send-async-failed: 0 # 异步发送重试0次

pay:
  ali:
    app-id: 2016***
    merchant-private-key: MIIEvg*****
    alipay-public-key: MIIBIj*****
    notify-url: http://localhost:8080/Alipay/notify_url.do
    return-url: http://localhost:8080/Alipay/alipay_return.do
    sign-type: RSA2
    charset: UTF-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
