server:
  port: 8079
spring:
  #session:
  #store-type: redis
  #timeout: 3600
  redis:
    host: localhost
    port: 6379
    database: 0
    password: Redis20868354
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL20868354

rocketmq:
  name-server: localhost:9876
  producer:
    group: kotlin-group # 当前应用是一个生产者，属于"kotlin-group"消费者组
    send-message-timeout: 300000 # 超时时间
    compress-message-body-threshold: 4096 # 压缩消息的阈值：4kb
    max-message-size: 4194304 # 消息最大4MB
    retry-times-when-send-failed: 2 # 发送失败后重试两次
    retry-next-server: true # 失败重试
    retry-times-when-send-async-failed: 0 # 异步发送重试0次

pay:
  ali:
    app-id: 2016***
    merchant-private-key: MIIEvg*****
    alipay-public-key: MIIBIj*****
    notify-url: http://localhost:8080/Alipay/notify_url.do
    return-url: http://localhost:8080/Alipay/alipay_return.do
    sign-type: RSA2
    charset: UTF-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
